# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "SimpleRssMailer"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
image_repositories = []
parameter_overrides = "RssUrlsSsmParameter=arn:aws:ssm:us-east-1:123456789012:parameter/RssEmailerZohoNotifier/rssUrls"
resolve_s3 = true
s3_prefix = "SimpleRssMailer"
tags = "Application=SimpleRssMailer"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
