AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploys Simple Rss Mailer to AWS

Parameters:
  RssUrlsSsmParameter:
    Type: AWS::SSM::Parameter::Name
    Description: SSM parameter that defines the RSS URLs to check as a JSON array, e.g. ["url1", "url2"]

Conditions:
  RssUrlsSsmParameterProvided: !Not [!Equals [!Ref RssUrlsSsmParameter, ""]]

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: Checks RSS feeds for new articles and sends email notifications
      CodeUri: rss
      Handler: simple_rss_mailer.handle
      #Architectures:
      #- arm64 # Can't use ARM on x86 without emulation in Docker, see https://github.com/aws/aws-sam-cli/issues/7523
      Environment:
        Variables:
          SNS_TOPIC_ARN: !GetAtt SnsTopic.TopicArn
          BUCKET: !Ref Bucket
          BUCKET_PATH: feeds
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            Name: CheckRssFeeds
            Description: Schedule to check RSS feeds
            FlexibleTimeWindow:
              MaximumWindowInMinutes: 15
              Mode: FLEXIBLE
            Input: !Sub '{"rss_urls": ["${RssUrlsSsmParameter}"]}' # RSS URL feeds to check. Or if the first URL is a AWS SSM parameter store ARN, retrieve RSS URLs from there instead
            ScheduleExpression: cron(0 19 * * ? *) # Everyday at 7PM UTC
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref Log
      MemorySize: 1024
      Policies: !If
        - RssUrlsSsmParameterProvided
        - Statement:
            Effect: Allow
            Action:
              - "ssm:GetParameter"
            Resource:
              - !Ref RssUrlsSsmParameter
        - !Ref 'AWS::NoValue'
      Runtime: python3.13
      Timeout: 60
      Tracing: Active
    Connectors:
      SNS:
        Properties:
          Destination:
            - Id: SnsTopic
          Permissions:
            - Write
      S3:
        Properties:
          Destination:
            - Id: Bucket
          Permissions:
            - Read
            - Write

  ZohoEmailerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Responds to SNS notifications be emailing via Zoho Mail API
      CodeUri: zoho
      Handler: zoho_emailer.handle
      #Architectures:
      #- arm64 # Can't use ARM on x86 without emulation in Docker, see https://github.com/aws/aws-sam-cli/issues/7523
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !GetAtt SnsTopic.TopicArn
      Environment:
        Variables:
          SSM_PARAMETER_PREFIX: /RssEmailerZohoNotifier # Leading slash, no trailing slash
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref Log
      MemorySize: 1024
      Policies:
        SSMParameterWithSlashPrefixReadPolicy:
          ParameterName: /RssEmailerZohoNotifier/*
      Runtime: python3.13
      Timeout: 60
      Tracing: Active

  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Topic for new RSS articles

  Log:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupClass: INFREQUENT_ACCESS
      RetentionInDays: 7

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  LambdaFunction:
    Description: Lambda Function ARN
    Value: !GetAtt LambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: Implicit IAM Role created for the Lambda function
    Value: !GetAtt LambdaFunctionRole.Arn
  TopicArn:
    Description: SNS Topic ARN
    Value: !GetAtt SnsTopic.TopicArn
